jobs:
- job: BUILD_LLVM
  timeoutInMinutes: 0

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - checkout: none

  - powershell: |
      git clone --config core.autocrlf=false --branch llvmorg-7.0.1 https://github.com/llvm/llvm-project.git 
      mkdir LLVM_BUILD
      mkdir LLVM_INSTALL
      cd LLVM_BUILD 
      cmake ..\llvm-project\llvm -G "Visual Studio 15 2017 Win64" -DLLVM_BUILD_TOOLS=Off -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_USE_CRT_DEBUG=MTd -DLLVM_USE_CRT_RELEASE=MT -DLLVM_BUILD_TESTS=Off -Thost=x64
      cmake --build . --target ALL_BUILD --config Release
      cmake --build . --target INSTALL -DCMAKE_INSTALL_PREFIX=..\LLVM_BUILD
      tree
      
#   - powershell: |
#       git clone --recursive https://github.com/grame-cncm/faust.git
      
#   - powershell: |
#       mkdir FAUST_BUILD
#       mkdir FAUST_INSTALL
#       cd FAUST_BUILD
#       .\cmake.exe -C iplug-backends.cmake -C iplug-targets-mac.cmake -DINCLUDE_STATIC=on -DINCLUDE_DYNAMIC=on -DINCLUDE_OSC=off -DINCLUDE_HTTP=off -DUNIVERSAL=off ../faust/build
#       .\cmake.exe -D CMAKE_INSTALL_PREFIX=FAUST_INSTALL ../faust/build
#       .\cmake.exe --build . --config Release -- -j 6
